# 1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [3]:

np.__version__
np.show_config

<function numpy.__config__.show()>

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a". 
#Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2,3,5))

# 4. Print a.

In [5]:
a

array([[[0.95856453, 0.83279242, 0.38825876, 0.99306681, 0.50308898],
        [0.2740162 , 0.21759683, 0.28133951, 0.43155065, 0.1343734 ],
        [0.93076802, 0.97630623, 0.20507724, 0.91826942, 0.15246013]],

       [[0.21601463, 0.49686188, 0.97293593, 0.11857635, 0.35672368],
        [0.72842685, 0.17017914, 0.1119708 , 0.38457764, 0.29500654],
        [0.10555446, 0.63113525, 0.34918829, 0.68477683, 0.88685451]]])

# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [6]:
b= np.ones((5,2,3))

# 6. Print b.

In [7]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# 7. Do a and b have the same size? How do you prove that in Python code?

In [24]:
if a.size == b.size:
    print('a and b have the same size')
else:
    print('a and b do not have the same size')

a and b have the same size


# 8. Are you able to add a and b? Why or why not?

In [26]:
if a.shape == b.shape:
    print('a and b have the same shape')
    print(a+b)
else:
    print('a y b no tienen la misma forma y por lo tanto no se pueden sumar')

a y b no tienen la misma forma y por lo tanto no se pueden sumar


# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [27]:
c= b.transpose((1,2,0)) ## Utilizamos el transpose en vez del .T porque sino el orden no lo podemos imponer y luego no habrá dimensiones iguales para poder sumar

In [28]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [29]:
d = a+c
print(d)
print(a)

[[[1.95856453 1.83279242 1.38825876 1.99306681 1.50308898]
  [1.2740162  1.21759683 1.28133951 1.43155065 1.1343734 ]
  [1.93076802 1.97630623 1.20507724 1.91826942 1.15246013]]

 [[1.21601463 1.49686188 1.97293593 1.11857635 1.35672368]
  [1.72842685 1.17017914 1.1119708  1.38457764 1.29500654]
  [1.10555446 1.63113525 1.34918829 1.68477683 1.88685451]]]
[[[0.95856453 0.83279242 0.38825876 0.99306681 0.50308898]
  [0.2740162  0.21759683 0.28133951 0.43155065 0.1343734 ]
  [0.93076802 0.97630623 0.20507724 0.91826942 0.15246013]]

 [[0.21601463 0.49686188 0.97293593 0.11857635 0.35672368]
  [0.72842685 0.17017914 0.1119708  0.38457764 0.29500654]
  [0.10555446 0.63113525 0.34918829 0.68477683 0.88685451]]]


Ahora si suma la matriz a con la matriz c, debido a que las dimensiones de las mismas son iguales.

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
a

array([[[0.95856453, 0.83279242, 0.38825876, 0.99306681, 0.50308898],
        [0.2740162 , 0.21759683, 0.28133951, 0.43155065, 0.1343734 ],
        [0.93076802, 0.97630623, 0.20507724, 0.91826942, 0.15246013]],

       [[0.21601463, 0.49686188, 0.97293593, 0.11857635, 0.35672368],
        [0.72842685, 0.17017914, 0.1119708 , 0.38457764, 0.29500654],
        [0.10555446, 0.63113525, 0.34918829, 0.68477683, 0.88685451]]])

In [17]:
d

array([[[1.95856453, 1.83279242, 1.38825876, 1.99306681, 1.50308898],
        [1.2740162 , 1.21759683, 1.28133951, 1.43155065, 1.1343734 ],
        [1.93076802, 1.97630623, 1.20507724, 1.91826942, 1.15246013]],

       [[1.21601463, 1.49686188, 1.97293593, 1.11857635, 1.35672368],
        [1.72842685, 1.17017914, 1.1119708 , 1.38457764, 1.29500654],
        [1.10555446, 1.63113525, 1.34918829, 1.68477683, 1.88685451]]])

In [18]:
np.array_equal(a,d)

False

La discrepancia entre los valores "d" y otros se debe a que los valores de "d" es el resultado de sumar uno a los valores de "a" y restarle los unod de la matriz "b".

# 12. Multiply a and c. Assign the result to e.

In [19]:
e=a*c
e

array([[[0.95856453, 0.83279242, 0.38825876, 0.99306681, 0.50308898],
        [0.2740162 , 0.21759683, 0.28133951, 0.43155065, 0.1343734 ],
        [0.93076802, 0.97630623, 0.20507724, 0.91826942, 0.15246013]],

       [[0.21601463, 0.49686188, 0.97293593, 0.11857635, 0.35672368],
        [0.72842685, 0.17017914, 0.1119708 , 0.38457764, 0.29500654],
        [0.10555446, 0.63113525, 0.34918829, 0.68477683, 0.88685451]]])

# 13. Does e equal to a? Why or why not?

In [31]:
print('a:')
print(a)
print('Shape:', a.shape)
print('Size:',a.size)
print('e:')
print(e)
print('Shape:', e.shape)
print('Size:',e.size)

if np.array_equal(a,e):
    print('a y e son iguales')
else:
    print('a y e son iguales')

a:
[[[0.95856453 0.83279242 0.38825876 0.99306681 0.50308898]
  [0.2740162  0.21759683 0.28133951 0.43155065 0.1343734 ]
  [0.93076802 0.97630623 0.20507724 0.91826942 0.15246013]]

 [[0.21601463 0.49686188 0.97293593 0.11857635 0.35672368]
  [0.72842685 0.17017914 0.1119708  0.38457764 0.29500654]
  [0.10555446 0.63113525 0.34918829 0.68477683 0.88685451]]]
Shape: (2, 3, 5)
Size: 30
e:
[[[0.95856453 0.83279242 0.38825876 0.99306681 0.50308898]
  [0.2740162  0.21759683 0.28133951 0.43155065 0.1343734 ]
  [0.93076802 0.97630623 0.20507724 0.91826942 0.15246013]]

 [[0.21601463 0.49686188 0.97293593 0.11857635 0.35672368]
  [0.72842685 0.17017914 0.1119708  0.38457764 0.29500654]
  [0.10555446 0.63113525 0.34918829 0.68477683 0.88685451]]]
Shape: (2, 3, 5)
Size: 30
a y e son iguales


# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [33]:
d_max = d.max()
print('d_max=', d_max)

d_max= 1.993066807962493


In [34]:
d_min = d.min()
print('d_min=', d_min)

d_min= 1.1055544591651145


In [35]:
d_mean =d.mean()
print('d_mean=', d_mean)

d_mean= 1.49021039728475


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [36]:
f = np.zeros_like(d, dtype=int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [46]:
d = [10, 20, 30, 40, 50]
f = [0] * len(d)
d_min = 10
d_mean = 30
d_max = 50

for i in range(len(d)):
    if d[i] > d_min and d[i] < d_mean:
        f[i] = 25
    elif d[i] > d_mean and d[i] < d_max:
        f[i] = 75
    elif d[i] == d_mean:
        f[i] = 50
    elif d[i] == d_min:
        f[i] = 0
    elif d[i] == d_max:
        f[i] = 100

print("f:", f)
print("d:", d)


f: [0, 25, 50, 75, 100]
d: [10, 20, 30, 40, 50]


# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
        Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [49]:
import numpy as np

# Define tu array "d"
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
              [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
              [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]],
             [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
              [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
              [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]])

f = np.zeros_like(d)


d_min = 1.3
d_mean = 1.6
d_max = 1.9


f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print("d:")
print(d)
print("f:")
print(f)


d:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
f:
[[[75. 75. 75. 25. 75.]
  [75. 75. 25. 75.  0.]
  [75.  0. 75. 75. 75.]]

 [[25. 25.  0. 25.  0.]
  [75. 75.  0. 75. 75.]
  [ 0.  0.  0.  0. 75.]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""